language: python
python:
  - "3.5" 
install: 
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  - python setup.py install
virtualenv:
  system_site_packages: false
script: 
  - pytest --cov=./ --cov-report=xml
  - codecov
  - pytest
branches:
  - master
  - first-pass
